name: Test Custom Action
on:
  workflow_dispatch: 
jobs:
  test-custom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Running the custom action
        uses: naveen-2003/github-actions-learning/.github/actions/custom-action
        with:
          name: "Naveen N"