name: First Github action
on:
  workflow_dispatch: 
jobs:
    echo-welcome:
      strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
      runs-on: ${{matrix.os}}
      steps:
        - name: Welcome message!
          run: echo "Welcome, Naveen!, Congrats on executing your first GitHub Actions...🎉"
        - name: Again Welcome from python
          shell: python
          run: print("Welcome again Naveen!!")
        - name: runs-on
          run: echo "$RUNNER_OS|$RUNNER_NAME"
           